In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import os

from sklearn.model_selection import train_test_split

In [23]:
#read the complete audio data
audio_df = pd.read_csv("audio_data/audio_data.csv")
audio_df

file_path target      mfcc_1  \
0    ../../data/music_audio/genres_original/pop/pop...    pop  -75.359413   
1    ../../data/music_audio/genres_original/pop/pop...    pop  -68.980240   
2    ../../data/music_audio/genres_original/pop/pop...    pop -113.163002   
3    ../../data/music_audio/genres_original/pop/pop...    pop  -73.372978   
4    ../../data/music_audio/genres_original/pop/pop...    pop  -18.168489   
..                                                 ...    ...         ...   
994  ../../data/music_audio/genres_original/jazz/ja...   jazz -192.113541   
995  ../../data/music_audio/genres_original/jazz/ja...   jazz -305.465393   
996  ../../data/music_audio/genres_original/jazz/ja...   jazz -414.082550   
997  ../../data/music_audio/genres_original/jazz/ja...   jazz -262.107971   
998  ../../data/music_audio/genres_original/jazz/ja...   jazz -261.824860   

         mfcc_2     mfcc_3     mfcc_4     mfcc_5     mfcc_6     mfcc_7  \
0     83.350716  10.695162  14.460500  14.239106   7.397378   5.280899   
1     73.761398 -12.468053   9.550569  -0.040610  12.724539   3.163581   
2     41.597984  21.517519  11.098094  17.437098   0.609657   3.029893   
3     97.491570  16.854250  -0.594387   7.181828   4.867855   0.757125   
4     72.283127  -4.891368  -0.376403   1.687277  -0.924446  -1.328674   
..          ...        ...        ...        ...        ...        ...   
994  105.568047 -26.025105  40.168938  -6.658175  26.505718 -10.386100   
995  121.930756   2.611254  36.931583  -8.555872  17.913818  -9.265583   
996  104.827606  -7.832920  37.852913   0.193289  23.407959  -7.296280   
997  108.990540  -6.340923  55.173943 -10.668641  18.520815  -4.250780   
998  139.535767 -17.112345  49.890068  -5.863275  19.849518   1.852981   

        mfcc_8  ...    mfcc_21   mfcc_22   mfcc_23   mfcc_24   mfcc_25  \
0    -0.393232  ...  -4.133138 -0.564807  2.511786  1.861522  2.008656   
1    -0.074320  ...  -1.215322 -3.088120 -2.131003 -0.855932 -1.190671   
2     0.085250  ...   0.540270  0.418499  2.248957  2.901232  1.801879   
3    -5.548040  ...  -4.247279 -4.255018 -1.603244 -0.137577  2.162586   
4    -0.342187  ...  -1.291154 -0.310522  1.586486  4.424511  3.441173   
..         ...  ...        ...       ...       ...       ...       ...   
994  18.473989  ...   1.357864  2.796630 -9.314795 -4.476328 -0.475076   
995  10.559932  ...  -1.974506 -4.846919 -3.861485 -6.043231  0.408348   
996   5.744218  ...  14.035221  8.379756  3.401259 -3.057804 -2.224388   
997  18.553394  ...  -1.289987 -2.115822 -1.353280  2.579172  4.604261   
998   5.711823  ...   0.394702  2.976537  2.973072 -0.251568  2.318126   

      mfcc_26   mfcc_27   mfcc_28   mfcc_29    mfcc_30  
0    2.581645 -1.264946 -4.423832 -2.666795   0.885556  
1   -1.264140  1.595003  1.488707  0.057162  -3.184187  
2   -0.424173  0.403642  0.366152  0.220694  -3.353836  
3    1.531331  0.779802  3.393496 -0.073624  -4.841033  
4    1.123244  0.915257 -1.361023 -1.526639  -3.263039  
..        ...       ...       ...       ...        ...  
994 -1.330312  3.952211 -3.554846  6.860224   3.824842  
995 -3.797377 -4.489580 -4.254775 -1.160770  -3.991522  
996 -3.990590  0.105034 -3.433403 -8.695078 -11.208939  
997 -5.802343 -6.631752 -4.681467 -0.587598  -4.265043  
998  1.369360 -1.943583  0.451709 -1.100677  -0.712416  

[999 rows x 32 columns]

## Train-test split

In [24]:
non_feature_columns = ['file_path', 'target']
feature_columns = [c for c in audio_df.columns if c not in non_feature_columns]
feature_columns

['mfcc_1',
 'mfcc_2',
 'mfcc_3',
 'mfcc_4',
 'mfcc_5',
 'mfcc_6',
 'mfcc_7',
 'mfcc_8',
 'mfcc_9',
 'mfcc_10',
 'mfcc_11',
 'mfcc_12',
 'mfcc_13',
 'mfcc_14',
 'mfcc_15',
 'mfcc_16',
 'mfcc_17',
 'mfcc_18',
 'mfcc_19',
 'mfcc_20',
 'mfcc_21',
 'mfcc_22',
 'mfcc_23',
 'mfcc_24',
 'mfcc_25',
 'mfcc_26',
 'mfcc_27',
 'mfcc_28',
 'mfcc_29',
 'mfcc_30']

In [25]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Assuming train_df is your DataFrame with 'target' as the class labels
X = audio_df.drop(non_feature_columns, axis=1)  # Features
y = audio_df['target']  # Class labels

# Perform the train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


In [26]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(799, 30)
(799,)
(200, 30)
(200,)


## Model Training

In [27]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


In [28]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)  # You can adjust n_estimators and other hyperparameters

print("fitting the model on the train data")
rf_model.fit(X_train, y_train)

fitting the model on the train data


RandomForestClassifier(random_state=42)

## Make Predictions

In [29]:
y_pred = rf_model.predict(X_test)
y_pred

array(['classical', 'blues', 'metal', 'jazz', 'disco', 'disco', 'reggae',
       'jazz', 'rock', 'jazz', 'blues', 'reggae', 'pop', 'metal',
       'reggae', 'pop', 'hiphop', 'jazz', 'metal', 'jazz', 'country',
       'metal', 'disco', 'country', 'metal', 'classical', 'classical',
       'country', 'jazz', 'jazz', 'blues', 'country', 'reggae', 'disco',
       'classical', 'metal', 'reggae', 'country', 'rock', 'disco',
       'reggae', 'rock', 'pop', 'metal', 'jazz', 'jazz', 'rock',
       'classical', 'reggae', 'pop', 'metal', 'metal', 'hiphop',
       'classical', 'reggae', 'pop', 'hiphop', 'classical', 'classical',
       'reggae', 'metal', 'reggae', 'hiphop', 'rock', 'reggae', 'disco',
       'rock', 'country', 'country', 'pop', 'metal', 'reggae',
       'classical', 'pop', 'reggae', 'hiphop', 'country', 'pop', 'pop',
       'pop', 'reggae', 'pop', 'reggae', 'hiphop', 'country', 'pop',
       'reggae', 'disco', 'metal', 'reggae', 'metal', 'reggae', 'metal',
       'disco', 'country',

## Measure the accuracy of the model

In [30]:
from sklearn.metrics import accuracy_score, confusion_matrix
acc = accuracy_score(y_test, y_pred)

print(f"The accuracy of the model is {acc*100} %")

The accuracy of the model is 59.5 %


In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(f"The Confusion Matrix is {cm}")

The Confusion Matrix is [[ 8  0  2  3  0  2  3  0  1  1]
 [ 1 17  1  0  0  1  0  0  0  0]
 [ 1  0 10  1  0  2  0  0  1  5]
 [ 0  0  1  9  1  0  1  3  2  3]
 [ 1  0  1  3  9  0  1  1  3  1]
 [ 0  2  1  2  0 11  0  1  3  0]
 [ 1  0  0  1  0  0 17  0  0  1]
 [ 0  1  0  1  0  0  0 17  0  1]
 [ 0  0  1  0  4  0  0  2 13  0]
 [ 1  0  3  2  0  1  1  1  3  8]]
